### ISSUE TITLE
PyInstaller is broken

### ISSUE THREAD

**Issue by shubham1172** [shubham1172/remote-play#21]
PyInstaller: 4.3
Python: 3.8.6
Platform: Windows-10-10.0.19041-SP0

```
Traceback (most recent call last):
  File "logging\config.py", line 388, in resolve
AttributeError: module 'uvicorn' has no attribute 'logging'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\config.py", line 390, in resolve
ModuleNotFoundError: No module named 'uvicorn.logging'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "logging\config.py", line 542, in configure
  File "logging\config.py", line 654, in configure_formatter
  File "logging\config.py", line 469, in configure_custom
  File "logging\config.py", line 397, in resolve
  File "logging\config.py", line 390, in resolve
ValueError: Cannot resolve 'uvicorn.logging.DefaultFormatter': No module named 'uvicorn.logging'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 115, in <module>
  File "uvicorn\main.py", line 375, in run
  File "uvicorn\config.py", line 205, in __init__
  File "uvicorn\config.py", line 251, in configure_logging
  File "logging\config.py", line 808, in dictConfig
  File "logging\config.py", line 545, in configure
ValueError: Unable to configure formatter 'default'
[22308] Failed to execute script main
```

**Comment by Torro** [comment]
I'm unable to reproduce this issue on ubuntu groovy (20.10) w. python 3.8.6, pyinstaller 4.2, and uvicorn 0.14.0

What version of uvicorn are you using?

**Comment by shubham1172** [comment]
@Torro, it's 0.13.4
```bash
$ pip show uvicorn
Name: uvicorn
Version: 0.13.4
Summary: The lightning-fast ASGI server.
Home-page: https://github.com/encode/uvicorn
Author: Tom Christie
Author-email: tom@tomchristie.com
License: BSD
Location: c:\users\shubhash\appdata\local\programs\python\python38\lib\site-packages
Requires: h11, click
Required-by:
```

**Comment by iddu01linux** [comment]
I think something like this has happened to me. Had to manually install the dependencies using `pip install`.
