### ISSUE TITLE
Graceful ws client disconnection

### ISSUE THREAD

**Issue by shubham1172** [shubham1172/remote-play#34]
On closing a remote-play tab in browser, the following logs appear on the server

```
Client disconnected.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\shubhash\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 184, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "C:\Users\shubhash\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\shubhash\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fastapi\applications.py", line 212, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\shubhash\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\shubhash\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\starlette\middleware\errors.py", line 146, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\shubhash\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\starlette\exceptions.py", line 58, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\shubhash\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\shubhash\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\starlette\routing.py", line 315, in handle
    await self.app(scope, receive, send)
  File "C:\Users\shubhash\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\starlette\routing.py", line 77, in app
    await func(session)
  File "C:\Users\shubhash\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fastapi\routing.py", line 273, in app
    await dependant.call(**values)
  File "C:\Users\shubhash\src\jason-remote-play\main.py", line 39, in websocket_endpoint
    await websocket.close()
  File "C:\Users\shubhash\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\starlette\websockets.py", line 142, in close
    await self.send({"type": "websocket.close", "code": code})
  File "C:\Users\shubhash\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\starlette\websockets.py", line 68, in send
    await self._send(message)
  File "C:\Users\shubhash\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 269, in asgi_send
    raise RuntimeError(msg % message_type)
RuntimeError: Unexpected ASGI message 'websocket.close', after sending 'websocket.close'.
INFO:     connection closed
```

This issue is for adding graceful handling of this event.

**Comment by idofish** [comment]
Hey, 
When the code gets to [this line](https://github.com/shubham1172/remote-play/blob/main/main.py#L47) the websocket has to be already closed since the only break in the while loop is in the `WebSocketDisconnect` exception handling. So calling `websocket.close()` raises an exception, removing this line fixed the problem for me

**Comment by shubham1172** [comment]
True, I think we can handle all the exceptions instead of just `WebSocketDisconnect`, and close the websocket for all the exceptions except `WebSocketDisconnect`. Something like this maybe.
```py
try:
    # do stuff`
catch WebSocketDisconnection:
    # log and break
catch Exception:
    # log, close socket, and break
```

**Comment by Miro114** [comment]
HI, I would like to contribute !
Can you please assign me this issue ?

**Comment by shubham1172** [comment]
Thanks @Miro114 for wanting to help out here. I would let @idofish decide if they want to fix it since they commented first, otherwise you can take it up!

**Comment by idofish** [comment]
Yeah I want to have a go at it, will upload a PR today

**Comment by idofish** [comment]
I'm getting a `W0703: Catching too general exception Exception (broad-except)` because I'm trying to `except Exception as error:`. I can try to catch only `PyAutoGUIException` but that will require an import, what do you think?

**Comment by shubham1172** [comment]
I think it should be okay to catch `Exception` because (1) we are already catching the specific exception above, and (2) we are logging the exception.

We can add a py-lint ignore comment for this error and provide the above as justification.
